### ISSUE TITLE
pcofix fails on some relations between unfolded values with explicit cofix

### ISSUE THREAD

**Issue by Lysxia** [snu-sf/paco#16]
Here is a minimized example. The `unfold` on the penultimate line somehow prevent the `pcofix` on the last line from going through. This is quite surprising as I wouldn't expect `unfold` to affect `pcofix`.  I'm quite uncertain of the cause, this may very well be a bug in Coq, in a standard tactic that `pcofix` uses.

```
Require Import Paco.paco.

Set Implicit Arguments.
Set Contextual Implicit.


CoInductive stream (A:Type) :=
| snil : stream A
| scons : A -> stream A -> stream A
.

Arguments scons {_} _ _.

Inductive seq_step (seq : stream nat -> stream nat -> Prop) :
  stream nat -> stream nat -> Prop :=
.
Hint Constructors seq_step.

Definition seq (s t : stream nat) := paco2 seq_step bot2 s t .
Hint Unfold seq.

Definition app (a : nat) : stream nat :=
  (cofix app := scons a snil).

Lemma seq_app : forall a, seq (app a) (app a).
Proof.
  unfold app. (* removing this line makes pcofix below succeed *)
  pcofix CH.
```

**Comment by gilhur** [comment]
Hi Xia,

Yes, that's kind of bug.
Thanks for reporting it.

I debugged my tactic and found that the problem occurs essentially due to weakness of the "reflexivity" tactic.

```
Lemma test: forall a, exists b, 
  (cofix app : stream nat := scons a snil) = (cofix app : stream nat := scons b snil).
Proof.
  intros.
  eexists. 
  (* instantiate (1:=a).  *)
  reflexivity. (* fails *)
```

In the above example, "reflexivity" fails unless we instantiate the evar with "a".
I think we can report this as kind of a bug with "reflexivity" or the unification engine.

Once "reflexivity" is strengthened, "pcofix" will work for the unfolded case.

Best,
Gil

**Comment by Lysxia** [comment]
This appears to be fixed for the next release of coq already. (see link to Coq's issue tracker just above)
